#!/bin/bash


set -e

source $(pwd)/auxel/loader


if [[ -z $1 ]]; then
    echo "Error : need additional paramater" &&
    exit
fi


if [[ $1 == "--reset" ]];then
   raptor_reset 
fi


if [[ $1 == "--install" ]];then
    rapto_makes
fi
